Books/urls.py
from django.urls import path
from .views import Books, BookDetailView

urlpatterns = [
    path('', Books.as_view(), name='books'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='book'),
]

HandRead/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Books.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Books/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField


def image_path(instance, file):
    return f'Authors/{instance.last_name} {instance.first_name}/{file}'


class Author(models.Model):
    last_name = models.CharField(_('Фамилия'), max_length=50)
    first_name = models.CharField(_('Имя'), max_length=50)
    patronymic = models.CharField(_('Отчество'), max_length=50, blank=True, null=True)
    pseudonym = models.CharField(_('Псевдоним'), max_length=50, blank=True, null=True)
    photo = models.ImageField(_('Фото'), upload_to=image_path, blank=True, null=True)
    date_of_birth = models.DateField(_('Дата рождения'))
    country = models.ForeignKey('Country', on_delete=models.CASCADE)
    biography = models.TextField(_('Биография'))

    class Meta:
        verbose_name = _('автор')
        verbose_name_plural = _('авторы')

    def full_name(self):
        return self.pseudonym if self.pseudonym else f'{self.first_name[0]}. {self.last_name}'

    def __str__(self):
        return self.pseudonym if self.pseudonym else f'{self.last_name} {self.first_name}'


class Country(models.Model):
    name = models.CharField(_('Страна'), max_length=50)

    class Meta:
        verbose_name = _('страна')
        verbose_name_plural = _('страны')

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(_('Название'), max_length=50)

    class Meta:
        verbose_name = _('жанр')
        verbose_name_plural = _('жанры')

    def __str__(self):
        return self.name


class Bibliography(models.Model):
    name = models.CharField(_('Название'), max_length=50)
    books = models.ManyToManyField('Book')

    class Meta:
        verbose_name = 'библиография'
        verbose_name_plural = 'библиографии'

    def __str__(self):
        return self.name


class Series(models.Model):
    name = models.CharField(_('Серия'), max_length=50)

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(_('Язык'), max_length=30)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(_('Название'), max_length=50)
    authors = models.ManyToManyField('Author', verbose_name=_('Авторы'))
    genres = models.ManyToManyField('Genre', verbose_name=_('Жанр'), blank=True)
    image = models.ImageField('Обложка', blank=True, null=True)
    series = models.ForeignKey('Series', on_delete=models.SET_NULL, verbose_name=_('серия'), blank=True, null=True)
    series_number = models.PositiveSmallIntegerField(_('Порядок в серии'), blank=True, null=True)
    publication_date = models.DateField(_('Дата публикации'))
    text = RichTextUploadingField('Текст')
    language = models.ForeignKey('Language', on_delete=models.CASCADE, null=True, verbose_name='Язык')

    class Meta:
        verbose_name = _('книга')
        verbose_name_plural = _('книги')

    def __str__(self):
        return f'{self.title}'

    def get_series(self):
        if self.series:
            return f'{self.series} ({self.series_number})'

    def get_authors(self):
        if self.authors.count() > 1:
            return {'data': ', '.join([author.full_name() for author in self.authors.all()]), 'title': 'Авторы'}
        return {'title': 'Автор', 'data': self.authors.first().full_name()}

    get_authors.short_description = 'Авторы'

    def get_image(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" height="250px" width="167px"/>')
        return

    get_image.short_description = 'Обложка'

    def get_genres(self):
        if self.genres.count() > 1:
            return ', '.join([genre.name for genre in self.genres.all()])
        return self.genres.first().name


class Keycap(models.Model):
    # language = models.ForeignKey('Language', on_delete=models.CASCADE, blank=True, null=True, verbose_name='Язык')
    position = models.PositiveIntegerField('Позиция')
    symbols = models.ManyToManyField('Symbol', verbose_name=_('Символы'))
    LEFT = 'Левый'
    RIGHT = 'Правый'
    SIDES = (
        (LEFT, 'Левый'),
        (RIGHT, 'Правый')
    )
    LITTLE = 1
    RING = 2
    MIDDLE = 3
    INDEX = 4
    THUMB = 5
    FINGERS = (
        ('1', LITTLE),
        ('2', RING),
        ('3', MIDDLE),
        ('4', INDEX),
        ('5', THUMB)
    )
    side = models.CharField(_('Сторона'), max_length=10, choices=SIDES, default=LEFT)
    finger = models.CharField(_('Палец'), max_length=15, choices=FINGERS, default=LITTLE)
    code = models.CharField('Код', max_length=15, blank=True, null=True)

    class Meta:
        verbose_name = 'Кнопка'
        verbose_name_plural = 'Кнопки'
        ordering = ('position',)

    def __str__(self):
        return f'{", ".join(self.symbols.values_list("name", flat=True))} - {self.position}'


class Symbol(models.Model):
    name = models.CharField('Кнопка', max_length=10)

    def __str__(self):
        return self.name

Books/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Book, Keycap


def index(request):
    books = Book.objects.all()
    return render(request, 'books/index.html', {'books': books})


class Books(ListView):
    model = Book
    ordering = 'id'
    template_name = 'books/index.html'


class BookDetailView(DetailView):
    model = Book
    template_name = 'books/book.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['keys_m'] = [15, 28]
        context['keys_l'] = [14, 29, 41]
        context['keys_xl'] = [42, 53]
        context['keys_xxl'] = [55, 56]
        context['keycaps'] = Keycap.objects.all()
        return context

templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

  </head>
  <body>
  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"></script>
  </body>
</html>

templates/books/book.html
{% extends "base.html" %}
{% block content %}
  {% load tags %}
{#  {% include 'keyboard.html' %}#}
{#  <div id="book">#}
{#    <h1>{{ book.title }}</h1>#}
{#    {% if book.series %}#}
{#      <p>{{ book.get_series }}</p>#}
{#    {% endif %}#}
{#    <p>{{ book.get_authors.data }}</p>#}
{#    <p>{{ book.publication_date|date:"d.m.Y" }}г.</p>#}
{#    <p>{{ book.get_genres }}</p>#}
{#  </div>#}
  <div id="text-container" style="margin: 0 auto" contenteditable="true" onselectstart="return false" onpaste="return false;" onCopy="return false" onCut="return false" onDrag="return false" onDrop="return false"  onblur="this.focus()" autofocus></div>
  <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  <script>
    const regex = /<[^<>]+>|(?<sym>[\b&\w\d;\b])+|(.+?)(?!<sym>)/g;
    const regexSym = /&(.*);/
    const symbols = {
      '-': [8211, 8210, 8212, 8213],
      '"': [8220, 8221, 8222, 8223],
    }

    function getText(text) {
      let dataArr = text.match(regex);
      let result = '';
      let word = '';
      let strLength = 0;
      let wordLength = 0;

      dataArr.forEach((item) => {
        if (item.length === 1 || regexSym.test(item)) {
          word += `<font>${item}</font>`;
          strLength++;
          wordLength++;
          if ([' ', '&para;'].includes(item)) {
            if (strLength <= 90) {
              result += word;
              if (item === '&para;') { strLength = 0; }
            } else {
              result += '<br>' + word;
              strLength = item === ' ' ? wordLength : 0;
            }
            word = '';
            wordLength = 0;
          }
        } else {
          result += item;
        }
      })
      return result
    }

    const text = getText(`{{ book.text|safe }}`);

    let inp = document.getElementById('text-container');
    inp.innerHTML = text

    let pos = 0;
    let errors = 0;
    let children = Array.from(inp.firstChild.children);

    inp.addEventListener('keypress', function (e) {
      if (!e.repeat) {
        if (e.key.charCodeAt(0) === inp.textContent.charCodeAt(pos) || symbols[e.key]) {
          inp.firstChild.children[pos].style.cssText = 'color: lightgrey';
          pos++;
          if (inp.firstChild.children[pos].tagName === 'BR') {
            children.splice(0, pos+1);
            inp.firstChild.innerHTML = children.map(e => e.outerHTML).join('')
            pos = 0;
            inp.firstChild.style.cssText = 'text-indent: 0;'
          }

          e.preventDefault();
          {#setCaret(inp, pos);#}
        } else if (e.key === 'Enter' && (inp.textContent.charCodeAt(pos) === 182)) {
          inp.firstChild.remove();
          if (inp.textContent === '') {
            if (confirm(`Книга прочитана!\nОшибок: ${errors}`)) {
              errors = 0
              inp.innerHTML = text;
            }
          }
          children = Array.from(inp.firstChild.children)

          pos = 0
          if (inp.firstChild.tagName === 'P') {
            inp.firstChild.style.cssText = 'text-indent: 20;'
          }
          e.preventDefault()

        } else {
          errors++;
          inp.firstChild.children[pos].classList.add('error');
          setTimeout(() => inp.firstChild.children[pos].classList.remove('error'), 200);
          e.preventDefault()
        }
      }
      e.preventDefault();
    });
  </script>

  <style>
    #text-container {
        padding: 10px;
        caret-color: transparent;
        width: max-content;
    }

    #text-container p {
        margin: 0 auto;
        text-indent: 20px;
    }

    .error {
        color: red;
    }

    blockquote {
      padding-left: 20px;
      padding-right: 8px;
      border-left: solid 5px #ccc;
      font-style: italic;3
      font-family: Georgia, Times, "Times New Roman", serif;
      margin-block-start: 1em;
      margin-block-end: 1em;
      margin-inline-start: 40px;
      margin-inline-end: 40px;
    }
  </style>
{% endblock content %}



      {#paragraphs.forEach((p) => {#}
      {#  let symbols = p.split('');#}
      {#  symbols.forEach((char, counter) => {#}
      {#    if (!(counter % 100) && counter > 0) {#}
      {#      tags.splice(insPos, 0, '<br>');#}
      {#      insPos++;#}
      {#    }#}
      {#    tags.splice(insPos, 0, char);#}
      {#    insPos++;#}
      {#  })#}
      {#  insPos += 2;#}
      {# })#}
      {#return tags.join('')#}

templates/books/index.html
{% extends "base.html" %}
{% block content %}
  {% for book in book_list %}
    <div>
      <h1>{{ book.title }}</h1>
      {{ book.get_image }}
      <p>{{ book.get_authors.title }}: {{ book.get_authors.data }}</p>
      <a href="{% url 'book' pk=book.pk %}">link</a>
    </div>
  {% endfor %}
{% endblock content %}

templates/keyboard.html
{% load tags %}
<div class="board">
  {% for keycap in keycaps %}
    <button id="{{ keycap.code }}" class="keycap
            {% if forloop.counter in keys_l %}
            key-l
            {% elif forloop.counter in keys_m %}
            key-m
            {% elif forloop.counter in keys_xl %}
            key-xl
            {% elif forloop.counter == 54 %}
            key-alt
            {% elif forloop.counter in keys_xxl %}
            key-xxl
            {% endif %}
            f{{ keycap.finger }}
            ">
      {% for symbol in keycap.symbols.all %}
        <div class="symbol">{{ symbol.name }}</div>
      {% endfor %}
    </button>
  {% endfor %}
</div>